name: CI on Competitions Runner
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
      - run: npm run build