name: Manual Deploy

on:
  workflow_dispatch:  # Запуск только вручную

jobs:
  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'  # Запуск только для main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run deployment script
        run: echo "Deploying application..."